---
galaxy_info:
  author: LionTech DevOps
  description: Deploy Apache web server with LionTech application
  company: LionTech
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
  galaxy_tags:
    - web
    - apache
    - httpd
    - deployment

dependencies: []